version: '3.8'

services:
  db:
    image: "postgres:13"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "DJANGO_SETTINGS_MODULE=educa.settings"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  memcached:
    image: 'bitnami/memcached:latest'
    ports:
    - 11211:11211
    environment:
      #- MEMCACHED_CACHE_SIZE=128
      #- MEMCACHED_MAX_CONNECTIONS=2000
      #- MEMCACHED_THREADS=4
      - MEMCACHED_USERNAME=admin
      - MEMCACHED_PASSWORD=A12345678a
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - memcached
      - redis

volumes:
  postgres_data: